permalink: none
sass:
    style: :compressed
sections:
- about
- how-to-get-there
collections:
- sections
- participants
- kiilopaa
- faq
- y2015
- y2016

defaults:
    -
        scope:
            path: "_participants"
        values:
            layout: "sub-page"
    -
        scope:
            path: "2015/participants"
        values:
            layout: "sub-page"
    -
        scope:
            path: "2016/participants"
        values:
            layout: "sub-page"
    -
        scope:
            path: "2015"
        values:
            layout: "index"
    -
        scope:
            path: "2016"
        values:
            layout: "index"
